shop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove')
]

shop/main/urls.py
from django.urls import path, include
from . import views

app_name = 'shop'

urlpatterns = [
    path("", views.product_list, name="main"),
    path("cart/", include(('cart.urls', 'cart'), namespace='cart')),
    path("account/", views.account, name="account"),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

shop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order_create, name='order_create')
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/cart/models.py
from django.db import models

# Create your models here.

shop/main/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField("Название", max_length=200, db_index=True)
    slug = models.SlugField("Slug", max_length=200, db_index=True, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("name",)
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField("Название", max_length=50)
    slug = models.SlugField("Slug", max_length=200, db_index=True)
    cover = models.ImageField("Фото", upload_to="images/", blank=True)
    description = models.CharField("Краткое описание", max_length=250)
    full_text = models.TextField("Основная информация")
    price = models.DecimalField("Цена", max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField("Количество")
    available = models.BooleanField("Наличие", default=True)
    created = models.DateTimeField("Создано", auto_now_add=True)
    updated = models.DateTimeField("Обновлено", auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("name",)
        index_together = (('id', 'slug'),)
        verbose_name = "Товар"
        verbose_name_plural = "Товары"

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

shop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, label = 'Количество', coerce=int, widget=forms.TextInput(attrs={
        'value': 1,
        'max': 20,
        'min': 1,
        'type': 'number',
    }))
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

shop/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST

from cart.cart import Cart
from cart.forms import CartAddProductForm
from main.models import Product


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    form = CartAddProductForm

    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'override': True})
    return render(request, 'main/cart.html', {'cart': cart,
                                              'form': form})

shop/main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from .models import Category, Product
from cart.forms import CartAddProductForm

from django.shortcuts import render, get_object_or_404
from .models import Category, Product


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'main/productlist.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    return render(request,
                  'main/detail.html',
                  {'product': product})


def account(request):
    return render(request, "main/account.html")


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'main/detail.html', {'product': product,
                                                        'cart_product_form': cart_product_form})

shop/main/templates/main/account.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}
    Account
{% endblock %}

{% block content %}

{% endblock %}

shop/main/templates/main/base.html
{% load static %}
{% load cart_extras %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}Meow Shop{% endblock %}</title>
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet" />
</head>
<body>
<div id="header">
    <ul><img src="{% static 'main/img/paws.svg' %}" id="paws"><a href="{% url 'shop:main' %}" class="logo">Meow Shop</a></ul>
<!--    <ul><form action="" method="get"><input type="search" class="search-bar" placeholder="Я ищу..." value aria-label="search" maxlength="100"></form></ul>-->
    <ul><button id="cartBtn">
    {% with total_items=cart|length %}
        {% if cart|length > 0 %}
            <a href="{% url 'cart:cart_detail' %}" class="cart"><img src="{% static 'main/img/cart.svg' %}">
                {{ total_items }} {{ total_items|ru_plural:"товар,товара,товаров" }},
                {{ cart.get_total_price }} ₽
            </a>
        {% else %}
            <a href="{% url 'cart:cart_detail' %}" class="cart"><img src="{% static 'main/img/cart.svg' %}"></a></button>
        {% endif %}
    {% endwith %}</button>
<!--        <button id="accBtn"><a href="{% url 'shop:account' %}" class="account">Аккаунт</a></button></ul>-->
</div>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
<footer>
    <p>Meow Shop ©2024.</p>
</footer>
</body>
</html>

shop/main/templates/main/cart.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}
    Cart
{% endblock %}

{% block content %}
    <h1>Корзина</h1>
    <table class="cart cartContent">
        <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}"><img class="loadedPhoto" src="{{ product.cover.url }}"></a>
                    </td>
                    <td class="cartText">{{ product.name }}</td>
                    <td class="cartText"><form action="{% url 'cart:cart_add' product.id %}" method="post">
                          <div>
                            {% csrf_token %}
                            <div>
                              {{ item.update_quantity_form.quantity }}
                              {{ item.update_quantity_form.override }}
                            </div>
                            <button class="btn" type="submit">Обновить</button>
                          </div>
                        </form> <br> {{ item.price }} ₽/ шт</td>
                    <td><a href="{% url 'cart:cart_remove' product.id%}"><img src="{% static 'main/img/trash.svg' %}"></a></td>
                    <td class="cartText">{{ item.total_price }} ₽</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price }} ₽</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'shop:product_list' %}">Перейти к покупкам</a>
    </p>
    <a href="{% url 'orders:order_create' %}">
        Заказать
    </a>

{% endblock %}

shop/main/templates/main/detail.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}
    Product
{% endblock %}

{% block content %}
    <div class="product-detail">
        <img class="loadedPhoto" src="{% if product.cover %}{{ product.cover.url }}{% else %}{% static 'main/img/NoImage.svg' %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <p class="price">{{ product.price }} ₽</p>
        <p class="stock">В наличии: {{ product.stock }} шт</p>
        <form action="{% url 'cart:cart_add' product.id %}" method="post">
            {% csrf_token %}
            {{ cart_product_form }}
            <button type="submit" id="addCartBtn" class="button">Добавить в корзину</button>
        </form>
        {{ product.description|linebreaks }}
        {{ product.full_text|linebreaks }}
    </div>
{% endblock %}

shop/main/templates/main/order_create.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}
    Checkout
{% endblock %}

{% block content %}
    <h1>Checkout</h1>
    <div class="order-info">
        <h3>Ваш заказ</h3>
        <ul>
            {% for item in cart %}
                <li>
                    {{ item.quantity }}x {{ item.product.name }}
                    <span>{{ item.total_price }} ₽</span>
                </li>
            {% endfor %}
        </ul>
        <p>Сумма заказа: {{ cart.get_total_price }} ₽</p>
    </div>
    <form action="." method="post" class="order-form">
        {{ form.as_p }}
        <p><input type="submit" value="Place order"></p>
        {% csrf_token %}
    </form>
{% endblock %}

shop/main/templates/main/order_created.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}
    Cart
{% endblock %}

{% block content %}
    <h1>Спасибо!</h1>
    <p>Ваш заказ был успешно создан. Номер вашего заказа:
        <strong>{{ order.id }}</strong>.</p>
{% endblock %}

shop/main/templates/main/productlist.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
    <div id="sidebar">
        <h3>Категории</h3>
        <ul>
            <li {% if not category %} class="selected"{% endif %}>
                <a href="{% url "shop:product_list" %}">All</a>
            </li>
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
        <h1>{% if category %}Товары категории {{ category.name }}{% else %}Все товары{% endif %}</h1>
        <div class="products-container">
            {% if products %}
                {% for product in products %}
                    <div class="product-container">
                        <a href="{{ product.get_absolute_url }}">
                            <img class="loadedPhoto" src="{% if product.cover %}{{ product.cover.url }}{% else %}{% static 'main/img/NoImage.svg' %}{% endif %}">
                        </a>
                        <h3>{{ product.name }}</h3>
                        <a>{{ product.price }} ₽</a>
                    </div>
                {% endfor %}
            {% else %}
                <p>Нет предложений по заданному фильтру</p>
            {% endif %}
        </div>
    </div>
{% endblock %}